apply plugin: 'com.android.application'
apply plugin: "org.sonarqube"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

android {
    namespace "ajitsingh.com.expensemanager"
    compileSdk 34

    defaultConfig {
        applicationId "ajitsingh.com.expensemanager"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    lint {
        baseline = file("lint-baseline.xml")
        checkAllWarnings = true
        abortOnError = true
    }

    testOptions {
        unitTests.all {
            systemProperty 'mockito.mock-maker', 'inline'
            jvmArgs(
                '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
                '--add-opens', 'java.base/java.lang.reflect=ALL-UNNAMED',
                '--add-opens', 'java.base/java.util=ALL-UNNAMED',
                '--add-opens', 'java.base/java.io=ALL-UNNAMED',
                '--add-opens', 'java.base/java.security=ALL-UNNAMED'
            )
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile(
                'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        excludes += 'LICENSE'
    }
}

sonar {
    properties {
        property "sonar.sources", "src/main"
        property "sonar.tests", "src/test,src/androidTest"

        property "sonar.exclusions", "**/build/**"

        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.organization", "bom254"
        property "sonar.projectKey", "bom254_Android_CI-CD"
        property "sonar.projectName", "Expense-Manager"
    }
}