name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: jetbrains
      #     java-version: 21
      #     cache: gradle

      # - name: Run Lint debug
      #   run: ./gradlew lintDebug

      - name: Upload Lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test: #for running tests withing the codebase present in the app/src folder
    needs: [lint]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Run tests
      #   run: ./gradlew test 

      # - name: Upload test report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: unit_test_report
      #     path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test: # for running android tests on the emulator
    needs: [unit-test]
    runs-on: macos-latest # Due to it's fast boot time,
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with: 
          api-level: 29
          script: ./gradlew connectedCheck

      - name: upload test report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
